name: CrossCI

on: pull_request

jobs:
  build:

    runs-on: macos-latest
      strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
          xcode: ['/Applications/Xcode_11.3.1.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
